---
name: Technical Issue
description: Report a technical issue or bug. A system administrator will soon contact you.
title: "Technical Issue"
labels: bug
assignees: themisAnagno
body:
  - type: input
    id: Name
    attributes:
      description: "Your Name"
      label: "Name"
      placeholder: "Example: Themistoklis Anagnostopoulos"
    validations:
      required: true
  - type: input
    id: email
    attributes:
      description: "Your email address"
      label: "Email"
      placeholder: "Example: tanangos@netcompany.com"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      description: "Describe the issue"
      label: "description"
    validations:
      required: true
---

